### ISSUE TITLE
Html5 bundle renaming

### ISSUE THREAD

**Issue by altus34** [Ovea/testatoo#73]
Renaming:
  - Paragraph => P
  - CheckBox => InputTypeCheckbox
  - Radio => InputTypeRadio

Create a Paragraph  in Testatoo core

**Comment by rochdev** [comment]
Why the change? I find the old names much easier to read.

**Comment by altus34** [comment]
No in fact it's confusing users cause:

For the TextField (the abstraction) you have InputTypeText (in the html5 implementation) so why for a Checkbox and Radio (the abstraction) you don't have InputTypeRadio and InputTypeCheckbox (in the html5 implementation)

The problem here it's that in fact the Html5 naming sucks. You can see this for the button case where you have two ways: Button tag or InputTypeButton ;(
